# In order to minimize real system damage, these files will get copied into the backup directory.
backup files: 
  - "/etc/sysconfig/network"
  - "/etc/hosts"
# One or many descriptions of the type that a user would report to the system administrator. 
description:
  - Apache does not run properly
# This is a long-winded explanation of exactly what is broken and how to fix it. This file only exists if the user decides to give up and needs a reference.
details: There is a hostname collision between /etc/hosts and /etc/sysconfig/network.  To fix it, resolve the redundancy.
# List of OS/Versions to which the module applies.
os requirements:
  - RHEL_3
  - RHEL_4
  - RHEL_5
  - RHEL_6
  - Fedora_2
  - Fedora_13
  - SUSE_9
# These packages must be installed for this package to be valid
package requirements:
  RHEL_3:
    - httpd
  RHEL_4:
    - httpd
  RHEL_5:
    - httpd
  RHEL_6:
    - httpd
  Fedora_2:
    - httpd
  Fedora_13:
    - httpd
  SUSE_9:
    - apache2
# These system calls must return true in order for this package to be valid, a - or ! preficing the the command indicates a perl file test, may need to enclose in quotes
system requirements:
  COMMON:
    - '-e "/etc/hosts"'
  RHEL_3:
    - 'chkconfig httpd on'
    - '-e "/etc/sysconfig/network"'
  RHEL_4:
    - 'chkconfig httpd on'
    - '-e "/etc/sysconfig/network"'
  RHEL_5:
    - 'chkconfig httpd on'
    - '-e "/etc/sysconfig/network"'
  RHEL_6:
    - 'chkconfig httpd on'
    - '-e "/etc/sysconfig/network"'
  Fedora_2:
    - 'chkconfig httpd on'
    - '-e "/etc/sysconfig/network"'
  Fedora_13:
    - 'chkconfig httpd on'
    - '-e "/etc/sysconfig/network"'
  SUSE_9:
    - 'chkconfig -f apache2 on'
# Actual trouble script
trouble script: apache-hostname_collision.pl
