# In order to minimize real system damage, these files will get copied into the backup directory.
backup files: 
  - "/etc/passwd"
# One or many descriptions of the type that a user would report to the system administrator. 
description:
  - Cannot log in at all
  - Cannot log in as root
# This is a long-winded explanation of exactly what is broken and how to fix it. This file only exists if the user decides to give up and needs a reference.
details: "/etc/passwd has been removed.  To fix it, restore from a backup or copy /etc/passwd- and manually re-add the most recent user"
# List of OS/Versions to which the module applies.
os requirements:
  - RHEL_3
  - RHEL_4
  - RHEL_5
  - RHEL_6
  - Fedora_2
  - Fedora_13
  - SUSE_9
# These packages must be installed for this package to be valid
package requirements:
#TODO: determine if files/nis/ldap/etc are being used, and only run for files
  COMMON:
    - setup
# These system calls must return true in order for this package to be valid, a - or ! preficing the the command indicates a perl file test, may need to enclose in quotes
system requirements:
  COMMON:
    - '-e "/etc/passwd"'
# Actual trouble script
trouble script: removepasswd.sh
