# In order to minimize real system damage, these files will get copied into the backup directory.
backup files: 
  - "/etc/securetty"
# One or many descriptions of the type that a user would report to the system administrator. 
description:
  - Cannot login as root
  - Cannot login to root via a console
# This is a long-winded explanation of exactly what is broken and how to fix it. This file only exists if the user decides to give up and needs a reference.
details: "/etc/securetty has been emptied.  To fix it, rebuild /etc/securetty or reinstall the setup rpm"
# List of OS/Versions to which the module applies.
os requirements:
  - RHEL_3
  - RHEL_4
  - RHEL_5
  - RHEL_6
  - Fedora_2
  - Fedora_13
  - SUSE_9
# These packages must be installed for this package to be valid
package requirements:
  COMMON:
    - setup
# These system calls must return true in order for this package to be valid, a - or ! preficing the the command indicates a perl file test, may need to enclose in quotes
system requirements:
  COMMON:
    - '-e "/etc/securetty"'
# Actual trouble script
trouble script: emptysecuretty.sh
