# In order to minimize real system damage, these files will get copied into the backup directory.
backup files: 
  - "/etc/inittab"
# One or many descriptions of the type that a user would report to the system administrator. 
description:
  - Graphical login is not working.
# This is a long-winded explanation of exactly what is broken and how to fix it. This file only exists if the user decides to give up and needs a reference.
details: the xfs server is not running.  To fix it, issue 'chkconfig xfs on' and 'service xfs start'.
# List of OS/Versions to which the module applies.
os requirements:
  - RHEL_3
  - RHEL_4
  - RHEL_5
  - RHEL_6
  - Fedora_2
  - Fedora_13
  - SUSE_9
# These packages must be installed for this package to be valid
package requirements:
  RHEL_3:
    - initscripts
    - XFree86-xfs
  RHEL_4:
    - initscripts
    - xorg-x11-xfs
  RHEL_5:
    - initscripts
    - xorg-x11-xfs
  RHEL_6:
    - initscripts
    - xorg-x11-xfs
  Fedora_2:
    - initscripts
    - xorg-x11-xfs
  Fedora_13:
    - initscripts
    - xorg-x11-xfs
  SUSE_9:
    - XFree86
    - aaa_base
# These system calls must return true in order for this package to be valid, a - or ! preficing the the command indicates a perl file test, may need to enclose in quotes
system requirements:
  COMMON:
    - '-e "/etc/inittab"'
# Actual trouble script
trouble script: disablexfs.sh
